### PR TITLE
feat: adds new test users

### PR DESCRIPTION
**Pull request by bartoszmajsak**
- adds new users to the cluster
- makes pwds configurable through env variables

### CODE REVIEW

**Comment by yxun** [comment]
Hi Bartosz, this PR is good to merge. 
I edited the branch from master to development. After my local test, I will merge this change from development branch to master.
If you need to use latest changes, you can check out development branch when master hasn't got updated.

Thanks,

**Comment by bartoszmajsak** [comment]
@yxun I think we might need `cluster-admin` for those users - where can I set it up in the scripts?

**Comment by yxun** [comment]
@bartoszmajsak we haven't wrote cluster-admin user creation step. We can check OpenShift 4 Doc. Either there is a way to create cluster-admin user or there is a way to update a regular user's privilege to a cluser-admin user.

**Comment by aslakknutsen** [comment]
oc adm policy add-cluster-role-to-user cluster-admin "user-name"

**Comment by yxun** [comment]
This PR has been merged into development and master branches.

**Pull request merged**
